/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package UserInterFace;

import java.awt.PopupMenu;
import javax.swing.JOptionPane;

/**
 *
 * @author ADMIN
 */
public class UI_StaffvsAD extends javax.swing.JFrame {

    /**
     * Creates new form UI_StaffvsAD
     */
    public UI_StaffvsAD() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        maytram = new javax.swing.JButton();
        dichvu = new javax.swing.JButton();
        baocao = new javax.swing.JButton();
        taikhoan = new javax.swing.JButton();
        camweb = new javax.swing.JButton();
        hotro = new javax.swing.JButton();
        jTextField1 = new javax.swing.JTextField();
        jTextField2 = new javax.swing.JTextField();
        dangxuat = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        Parent = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setPreferredSize(new java.awt.Dimension(900, 600));

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));
        jPanel2.setPreferredSize(new java.awt.Dimension(1000, 50));
        jPanel2.setLayout(null);

        maytram.setFont(new java.awt.Font("Segoe UI", 1, 11)); // NOI18N
        maytram.setText("Máy Trạm");
        maytram.setPreferredSize(new java.awt.Dimension(70, 20));
        maytram.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                maytramActionPerformed(evt);
            }
        });
        jPanel2.add(maytram);
        maytram.setBounds(6, 29, 93, 35);

        dichvu.setFont(new java.awt.Font("Segoe UI", 1, 11)); // NOI18N
        dichvu.setText("Dịch vụ");
        dichvu.setPreferredSize(new java.awt.Dimension(70, 20));
        dichvu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                dichvuActionPerformed(evt);
            }
        });
        jPanel2.add(dichvu);
        dichvu.setBounds(197, 29, 81, 35);

        baocao.setFont(new java.awt.Font("Segoe UI", 1, 11)); // NOI18N
        baocao.setText("Báo cáo");
        baocao.setPreferredSize(new java.awt.Dimension(70, 20));
        baocao.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                baocaoActionPerformed(evt);
            }
        });
        jPanel2.add(baocao);
        baocao.setBounds(284, 29, 84, 35);

        taikhoan.setFont(new java.awt.Font("Segoe UI", 1, 11)); // NOI18N
        taikhoan.setText("Tài khoản");
        taikhoan.setPreferredSize(new java.awt.Dimension(70, 20));
        taikhoan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                taikhoanActionPerformed(evt);
            }
        });
        jPanel2.add(taikhoan);
        taikhoan.setBounds(105, 29, 86, 35);

        camweb.setFont(new java.awt.Font("Segoe UI", 1, 11)); // NOI18N
        camweb.setText("Cấm web");
        camweb.setPreferredSize(new java.awt.Dimension(70, 20));
        camweb.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                camwebActionPerformed(evt);
            }
        });
        jPanel2.add(camweb);
        camweb.setBounds(460, 29, 90, 35);

        hotro.setFont(new java.awt.Font("Segoe UI", 1, 11)); // NOI18N
        hotro.setText("Hổ trợ");
        hotro.setPreferredSize(new java.awt.Dimension(70, 20));
        hotro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                hotroActionPerformed(evt);
            }
        });
        jPanel2.add(hotro);
        hotro.setBounds(374, 29, 80, 35);

        jTextField1.setText(" ");
        jPanel2.add(jTextField1);
        jTextField1.setBounds(618, 27, 80, 39);

        jTextField2.setText(" ");
        jPanel2.add(jTextField2);
        jTextField2.setBounds(716, 27, 80, 39);

        dangxuat.setFont(new java.awt.Font("Segoe UI", 1, 11)); // NOI18N
        dangxuat.setText("Đăng xuất");
        dangxuat.setPreferredSize(new java.awt.Dimension(70, 20));
        dangxuat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                dangxuatActionPerformed(evt);
            }
        });
        jPanel2.add(dangxuat);
        dangxuat.setBounds(864, 29, 120, 35);

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/anh1.gif"))); // NOI18N
        jPanel2.add(jLabel2);
        jLabel2.setBounds(-3, -10, 1000, 80);

        Parent.setBackground(new java.awt.Color(255, 255, 255));
        Parent.setLayout(new java.awt.CardLayout());

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/anh23(ct).gif"))); // NOI18N
        Parent.add(jLabel1, "card2");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(Parent, javax.swing.GroupLayout.PREFERRED_SIZE, 1000, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, 74, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(Parent, javax.swing.GroupLayout.PREFERRED_SIZE, 520, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 1000, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void maytramActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_maytramActionPerformed
        Parent.removeAll();
        PnMayTram mt = new PnMayTram();
        mt.displayDataFromDatabase();
        Parent.add(mt);
        Parent.revalidate();
        Parent.repaint();
    }//GEN-LAST:event_maytramActionPerformed

    private void dichvuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_dichvuActionPerformed
        Parent.removeAll();
        PnDichVu dv = new PnDichVu();
        dv.displayDataFromDatabase();
        Parent.add(dv);
        Parent.revalidate();
        Parent.repaint();
    }//GEN-LAST:event_dichvuActionPerformed

    private void baocaoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_baocaoActionPerformed
        Parent.removeAll();
        PnBaoCao bc = new PnBaoCao();
        Parent.add(bc);
        Parent.revalidate();
        Parent.repaint();
    }//GEN-LAST:event_baocaoActionPerformed

    private void taikhoanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_taikhoanActionPerformed
        Parent.removeAll();
        PnTaiKhoan tk = new PnTaiKhoan();
        tk.displayDataFromDatabase();
        Parent.add(tk);
        Parent.revalidate();
        Parent.repaint();
    }//GEN-LAST:event_taikhoanActionPerformed

    private void camwebActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_camwebActionPerformed
        Parent.removeAll();
        PnCamWeb cw = new PnCamWeb();
        Parent.add(cw);
        Parent.revalidate();
        Parent.repaint();
    }//GEN-LAST:event_camwebActionPerformed

    private void hotroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_hotroActionPerformed
        Parent.removeAll();
        PnHoTro ht = new PnHoTro();
        Parent.add(ht);
        Parent.revalidate();
        Parent.repaint();
    }//GEN-LAST:event_hotroActionPerformed

    private void dangxuatActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_dangxuatActionPerformed
        // Mã xử lý đăng xuất
        JOptionPane.showMessageDialog(this, "Bạn đã đăng xuất");
        // Thêm mã để đóng cửa sổ hoặc chuyển đến cửa sổ đăng nhập
        this.dispose(); // Đóng cửa sổ hiện tại (nếu đó là cửa sổ đăng nhập)
    }//GEN-LAST:event_dangxuatActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(UI_StaffvsAD.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(UI_StaffvsAD.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(UI_StaffvsAD.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(UI_StaffvsAD.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new UI_StaffvsAD().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel Parent;
    private javax.swing.JButton baocao;
    private javax.swing.JButton camweb;
    private javax.swing.JButton dangxuat;
    private javax.swing.JButton dichvu;
    private javax.swing.JButton hotro;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JButton maytram;
    private javax.swing.JButton taikhoan;
    // End of variables declaration//GEN-END:variables
}
