/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package group2.LoginVsLogout;

import UserInterFace.AccountControl;
import UserInterFace.UI_Customers;
import javax.swing.JOptionPane;
import java.awt.BorderLayout;
import javax.swing.SwingUtilities;

/**
 *
 * @author ADMIN
 */
public class dangnhap extends javax.swing.JPanel {

    AccountControl accoutControl;
    private UI_Customers bandieukhien;
    private void showBangDieuKhien(){
        bandieukhien = new UI_Customers();
        bandieukhien.setVisible(true);
        // Đóng cửa sổ đăng nhập nếu cần thiết
        SwingUtilities.getWindowAncestor(this).dispose();
    }
    public dangnhap() {
        initComponents();
        accoutControl = new AccountControl();
    }

    public static void main(String[] args) {
        // Create and display the form
        
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new dangnhap().setVisible(true);
            }
        });
       javax.swing.JFrame frame = new javax.swing.JFrame("Đăng nhập");

        // Create an instance of dangnhap panel
        dangnhap loginPanel = new dangnhap();

        // Add the panel to the frame's content pane
        frame.getContentPane().add(loginPanel);

        // Set default close operation and pack the frame
        frame.setDefaultCloseOperation(javax.swing.JFrame.EXIT_ON_CLOSE);
        frame.pack();

        // Set the frame to be visible
        frame.setVisible(true);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        userNameLable = new javax.swing.JLabel();
        passwordLable = new javax.swing.JLabel();
        userNameField = new javax.swing.JTextField();
        passwordField = new javax.swing.JTextField();
        buttonLogin = new javax.swing.JButton();
        buttonExit = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setPreferredSize(new java.awt.Dimension(400, 300));

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setLayout(null);

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("ĐĂNG NHẬP");
        jPanel1.add(jLabel2);
        jLabel2.setBounds(140, 50, 150, 40);

        userNameLable.setFont(new java.awt.Font("Segoe UI", 1, 13)); // NOI18N
        userNameLable.setForeground(new java.awt.Color(255, 255, 0));
        userNameLable.setText("Tên đăng nhập");
        jPanel1.add(userNameLable);
        userNameLable.setBounds(80, 120, 91, 25);

        passwordLable.setFont(new java.awt.Font("Segoe UI", 1, 13)); // NOI18N
        passwordLable.setForeground(new java.awt.Color(255, 255, 0));
        passwordLable.setText("Mật khẩu");
        jPanel1.add(passwordLable);
        passwordLable.setBounds(80, 150, 70, 25);

        userNameField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                userNameFieldActionPerformed(evt);
            }
        });
        jPanel1.add(userNameField);
        userNameField.setBounds(190, 120, 129, 25);
        jPanel1.add(passwordField);
        passwordField.setBounds(190, 150, 129, 25);

        buttonLogin.setText("Đăng nhập");
        buttonLogin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonLoginActionPerformed(evt);
            }
        });
        jPanel1.add(buttonLogin);
        buttonLogin.setBounds(80, 220, 88, 23);

        buttonExit.setText("Thoát");
        buttonExit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonExitActionPerformed(evt);
            }
        });
        jPanel1.add(buttonExit);
        buttonExit.setBounds(240, 220, 72, 23);

        jLabel1.setForeground(new java.awt.Color(255, 255, 0));
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/hinh-nen-gaming-48.jpg"))); // NOI18N
        jLabel1.setText("ĐĂNG NHẬP");
        jPanel1.add(jLabel1);
        jLabel1.setBounds(0, -10, 400, 310);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents

    private void userNameFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_userNameFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_userNameFieldActionPerformed

    private void buttonExitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonExitActionPerformed
        // TODO add your handling code here:
        System.exit(0);
    }//GEN-LAST:event_buttonExitActionPerformed

    private void buttonLoginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonLoginActionPerformed
            String username = userNameField.getText().trim();
            String password = passwordField.getText().trim();
        if (!username.equals("") && !password.equals("")) {
            Boolean check = accoutControl.login(username, password);
            if (check == true) {
                
                JOptionPane.showMessageDialog(this, "Đăng nhập thành công!");
                showBangDieuKhien();
            } else {
                JOptionPane.showConfirmDialog(this, "username hoặc password không đúng", "lỗi", JOptionPane.ERROR_MESSAGE);
            }
        } else {
            JOptionPane.showConfirmDialog(this, "username hoặc password chưa nhập", "lỗi", JOptionPane.ERROR_MESSAGE);

        }
    }//GEN-LAST:event_buttonLoginActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton buttonExit;
    private javax.swing.JButton buttonLogin;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextField passwordField;
    private javax.swing.JLabel passwordLable;
    private javax.swing.JTextField userNameField;
    private javax.swing.JLabel userNameLable;
    // End of variables declaration//GEN-END:variables
}
